name: Python tests + deploy
on:
  push:
    branches:
      - main
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: tlambert03/setup-qt-libs@v1
      
      - name: Install dependencies
        run: |
          cd python # NOTE: move to python directory
          python -m pip install --upgrade pip
          pip install pre-commit pytest pytest-qt napari[all]
          pip install .

      # Update output format to enable automatic inline annotations.
      - name: Run pre-commit
        run: |
          cd python
          pre-commit run --all-files

      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: |
            cd python
            pytest -vv .
        env:
          PLATFORM: ubuntu-latest
          BACKEND: pyqt5
  
  deploy:
    # this will run when you have tagged a commit, starting with "v*"
    # and requires that you have put your twine API key in your
    # github secrets (see readme for details)
    needs: [test]
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags')
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U wheel twine build
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_API_KEY }}
        run: |
          git tag
          cd python
          python -m build .
          twine upload dist/*
