name: Python linting & tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: python  # NOTE: move to python directory
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit pytest
          pip install .

      # Update output format to enable automatic inline annotations.
      - name: Run pre-commit
        working-directory: python
        run: pre-commit run --all-files

      - name: Run tests
        working-directory: python
        run: pytest -vv .
